public class MathematicalClass {
    public integer addition(integer a, integer b) {
        integer add = a + b;
        return add;
    }
    public integer subtraction(integer a, integer b) {
        integer subtract = a - b;
        return subtract;
    }
    public integer multiplication(integer a, integer b) {
        integer multiply = a * b;
        return multiply;
    }    
    public integer division(integer a, integer b) {
        integer divide = a / b;
        return divide;
    }

}
